# Generated by Django 5.2.5 on 2025-11-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('shipped', 'shipped')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=120)),
                ('shipping_postal_code', models.CharField(blank=True, max_length=30)),
                ('shipping_country', models.CharField(blank=True, max_length=120)),
                ('shipping_phone', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
